name: Deploy

on:
  workflow_dispatch: # Put here!!
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vuhoanghung
          password: vhh1812477

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: uyphong99/express-app:latest
